### ISSUE TITLE
Install Failure: Mojo::Template

### ISSUE THREAD

**Issue by lancew** [tadzik/Bailador#23]
When installing with panda I received the following error:

===SORRY!===
Could not find Template::Mojo in any of: /home/lancew/.panda-work/1428163693_5/blib/lib, /home/lancew/.panda-work/1428163693_5/lib, /home/lancew/.perl6/2015.03, /usr/languages/perl6/lib, /usr/languages/perl6, /usr/languages/perl6/site
build stage failed for Bailador: Failed building lib/Bailador/Template/Mojo.pm
  in method install at lib/Panda.pm:122
  in method resolve at lib/Panda.pm:198
  in sub MAIN at /home/lancew/.perl6/2015.03/45:20
  in sub MAIN at /home/lancew/.perl6/2015.03/45:18
  in block <unit> at /home/lancew/.perl6/2015.03/45:82

Attempted to manually install Temaple::Mojo. This did not resolve the issue.
Attempted: panda install Bailador::Template::Mojo This also did not solve issue

**Comment by moritz** [comment]
FWIW https://github.com/tadzik/Template-Mojo/pull/17 fixes that.

**Comment by tadzik** [comment]
Fixed by PR 17, thanks for reporting :)
