### ISSUE TITLE
Not working after glr merge

### ISSUE THREAD

**Issue by mj41** [tadzik/Bailador#32]
Otput of: [pre-glr-debug.sh](https://gist.github.com/mj41/55e6121e3b0380f66fec) t/01-route-existance.t
Work in progress: https://github.com/mj41/Bailador/commits/mj-glr-fix

<pre>

====================================================================================
origin	git@github.com:mj41/Bailador.git (fetch)
origin	git@github.com:mj41/Bailador.git (push)
up	git@github.com:tadzik/Bailador.git (fetch)
up	git@github.com:tadzik/Bailador.git (push)
====================================================================================
Output of 'git log -1 ; git diff HEAD~1':
commit 1fcfc3cea0cee92b2e1a90410808f069f2382599
Author: Michal Jurosz <mj@mj41.cz>
Date:   Sat Sep 5 12:55:12 2015 +0200

    !!! Debug
diff --git a/t/01-route-existance.t b/t/01-route-existance.t
index 16d2c5e..2a4da9e 100644
--- a/t/01-route-existance.t
+++ b/t/01-route-existance.t
@@ -11,6 +11,7 @@ post '/bar' => sub { }
 post '/echo3/:text' => sub ($text) { return 'Echo3: ' ~ join('-', $text,  (request.params<text> // ''), (request.params('body')<text> // ''), (request.params('query')<text> // ''))}
 
 is-deeply get-psgi-response('GET', '/foo'),  [200, ["Content-Type" => "text/html"], Any],              'route GET /foo exists';
+exit;
 is-deeply get-psgi-response('POST', '/foo'), [404, ["Content-Type" => "text/html"], 'Not found'], 'route POST /foo does not exist';
 is-deeply get-psgi-response('POST', '/bar'), [200, ["Content-Type" => "text/html"], Any],              'route POST /bar exists';
 is-deeply get-psgi-response('GET', '/bar'),  [404, ["Content-Type" => "text/html"], 'Not found'], 'route GET /bar does not exist';
====================================================================================

====================================================================================
Switching to moar-pre-glr
Updating shims
====================================================================================
1..27
ok 1 - route GET /foo exists
# Looks like you planned 27 tests, but ran 1
====================================================================================

====================================================================================
Switching to moar-nom
Updating shims
====================================================================================
1..27
not ok 1 - route GET /foo exists

# Failed test 'route GET /foo exists'
# at t/01-route-existance.t line 13
# expected: [200, [:Content-Type("text/html")], Any]
#      got: [200, [:Content-Type("text/html")], [Any]]
# Looks like you planned 27 tests, but ran 1
# Looks like you failed 1 test of 1
====================================================================================

</pre>

**Comment by lizmat** [comment]
the test was fixed by flatting @.contents.  Am not sure that's the right approach though, since you want to be liberal in what you expect as Bailador.  So maybe route should do the flattening as needed ?

**Comment by mj41** [comment]
Note: panda Bailador is blocked also by https://github.com/softmoth/p6-Template-Mustache/issues/10

**Comment by mj41** [comment]
https://github.com/tadzik/Bailador/pull/33 merged
